name: Zig Continuous Integration

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  test-zig:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - uses: actions/checkout@v4
      - name: Test Zig files
        run: |
          zig build -freference-trace
          zig build test -freference-trace
